name: ulicastefankowa
description: The app/webpage for ulica stefankowa

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  rxdart: ^0.26.0-nullsafety.0
  url_launcher: ^6.0.0-nullsafety.1
  flusmic: 2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  path_provider: ^1.6.24
  equatable: ^2.0.0-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/header.jpg
    - images/header-dark.png
    - images/logo.png
    - images/aga.jpg
  fonts:
    - family: Serif
      fonts:
        - asset: fonts/PT_Serif-Web-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

