name: ulicastefankowa
description: A new Flutter project.

dependencies:
  rxdart: ^0.25.0
  url_launcher: ^5.7.10
  flusmic: 2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  intl_translation: ^0.17.0
  path_provider: ^1.6.24
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/header.jpg
    - images/header-dark.png
    - images/logo.png
    - images/aga.jpg
  fonts:
    - family: Serif
      fonts:
        - asset: fonts/PT_Serif-Web-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
